defaults:
- _self_
- mlflow: default
- trainer: default
- model: less_basic_nn
- data: default

random_state: 38
checkpoint_path: './data/checkpoints/best-model-loss-valid_loss=0.23-epoch-epoch=49.ckpt'